replicaCount: 1

image:
  repository: confluentinc/cp-kafka
  tag: 7.5.0

ports:
  external: 9092
  internal: 29092

config:
  brokerId: "1"
  zookeeperConnect: "zookeeper:2181"
  listenerSecurityProtocolMap: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
  advertisedListeners: "PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092"
  offsetsTopicReplicationFactor: "1"
