replicaCount: 1

image:
  repository: lordsecond/validation
  tag: latest

service:
  port: 8082

configserver:
  port: 8888

fluentd:
  enabled: true
  address: fluentd.logging.svc.cluster.local:24224
