---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: validation
  template:
    metadata:
      labels:
        app: validation
    spec:
      initContainers:
        - name: wait-for-configserver
          image: busybox
          command: [ 'sh', '-c', 'until nc -z configserver {{ .Values.configserver.port }}; do echo waiting for configserver; sleep 5; done' ]
      containers:
        - name: validation
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-openai-secret
                  key: OPENAI_API_KEY
            - name: LOKI_URL
              valueFrom:
                configMapKeyRef:
                  key: LOKI_URL
                  name: common-config
            - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  key: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
                  name: common-config
            - name: SPRING_CONFIG_IMPORT
              value: "optional:configserver:http://configserver.default.svc.cluster.local:{{ .Values.configserver.port }}"
            - name: LOGGING_DRIVER
              value: fluentd
            - name: FLUENTD_ADDRESS
              value: fluentd.logging.svc.cluster.local:24224
          ports:
            - containerPort: {{ .Values.service.port }}
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.service.port }}
            initialDelaySeconds: 60
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.service.port }}
            initialDelaySeconds: 60
            periodSeconds: 20
          volumeMounts:
            - name: logs
              mountPath: /var/log
      volumes:
        - name: logs
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    app: validation
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
#data:
# SPRING_DATASOURCE_URL: "jdbc:mysql://mysql.default.svc.cluster.local:3306/inventory_service"
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-openai-secret
type: Opaque
data:
  OPENAI_API_KEY: "c2stcHJvai1CQW8zcnd6NkkxdnZtU2JpNXFmQlFlZHYtR2ZfSEJNTUVlc3ZrWm8yMDhSSVB6YW9yQkpHcUNkQW5kbF9QeHl3VFRfVWlnY190TlQzQmxia0ZKMDBTcThmMUZIWWt2Z0hQUjZXczlYSU5qbVZFcS12bFNqME1FRmNnRzlhYWVlOW84UU1oTlpabExwZHJiYjdvX05DbzZ6VklqWUE="
