replicaCount: 1

image:
  repository: lordsecond/workout
  tag: latest

service:
  port: 8081

configserver:
  port: 8888

config:
  datasourceUrl: "jdbc:mysql://mysql.dev.svc.cluster.local:3306/workout_dev"
  schemaRegistryUrl: "http://schema-registry.dev.svc.cluster.local:8081"
