apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Release.Name }}-fluentd
  namespace: {{ .Release.Namespace }}
  labels:
    app: fluentd
spec:
  selector:
    matchLabels:
      app: fluentd
  template:
    metadata:
      labels:
        app: fluentd
    spec:
      containers:
        - name: fluentd
          image: {{ .Values.fluentd.image.repository }}:{{ .Values.fluentd.image.tag }}
          env:
            - name: FLUENT_ELASTICSEARCH_HOST
              value: {{ .Values.elasticsearch.host }}
            - name: FLUENT_ELASTICSEARCH_PORT
              value: {{ .Values.elasticsearch.port | quote }}
          volumeMounts:
            - name: varlog
              mountPath: /var/log
            - name: containers
              mountPath: /var/lib/docker/containers
              readOnly: true
            - name: fluentd-config
              mountPath: /fluentd/etc
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: containers
          hostPath:
            path: /var/lib/docker/containers
        - name: fluentd-config
          configMap:
            name: fluentd-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: {{ .Release.Namespace }}
data:
  fluent.conf: |
    <source>
      @type forward
      port 24224
    </source>
    <match **>
      @type elasticsearch
      host ${FLUENT_ELASTICSEARCH_HOST}
      port ${FLUENT_ELASTICSEARCH_PORT}
      logstash_format true
    </match>