replicaCount: 1

image:
  repository: lordsecond/gateway
  tag: latest

service:
  port: 9000

configserver:
  port: 8888

config:
  jwtIssuerUri: "http://34.118.122.132:31824/realms/spring-microservices-security-realm"
