apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:v2.46.0
          ports:
            - containerPort: 9090
          args:
            - --enable-feature=exemplar-storage
            - --config.file=/etc/prometheus/prometheus.yml
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus
      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  selector:
    app: prometheus
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-configmap
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s
      evaluation_interval: 5s
    
    scrape_configs:
      - job_name: 'gateway'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['gateway.default.svc.cluster.local:9000'] ## only for demo purposes don't use host.docker.internal in production replace with the container name
      - job_name: 'exercise'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['exercise.default.svc.cluster.local:8080'] ## only for demo purposes don't use host.docker.internal in production replace with the container name
            labels:
              application: 'Exercise Service'
      - job_name: 'workout'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['workout.default.svc.cluster.local:8081'] ## only for demo purposes don't use host.docker.internal in production replace with the container name
            labels:
              application: 'Workout Service'
      - job_name: 'validation'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['validation.default.svc.cluster.local:8082'] ## only for demo purposes don't use host.docker.internal in production replace with the container name
            labels:
              application: 'Validation Service'
      - job_name: 'notification'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['notification.default.svc.cluster.local:8083'] ## only for demo purposes don't use host.docker.internal in production replace with the container name
            labels:
              application: 'Notification Service'