---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: kafka-ui
  template:
    metadata:
      labels:
        app: kafka-ui
    spec:
      containers:
        - name: kafka-ui
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: KAFKA_CLUSTERS_NAME
              valueFrom:
                configMapKeyRef:
                  key: KAFKA_CLUSTERS_NAME
                  name: {{ .Release.Name }}-config
            - name: KAFKA_CLUSTERS_BOOTSTRAPSERVERS
              valueFrom:
                configMapKeyRef:
                  key: KAFKA_CLUSTERS_BOOTSTRAPSERVERS
                  name: {{ .Release.Name }}-config
            - name: DYNAMIC_CONFIG_ENABLED
              valueFrom:
                configMapKeyRef:
                  key: DYNAMIC_CONFIG_ENABLED
                  name: {{ .Release.Name }}-config
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  type: NodePort
  selector:
    app: kafka-ui
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  KAFKA_CLUSTERS_NAME: "{{ .Values.config.clusterName }}"
  KAFKA_CLUSTERS_BOOTSTRAPSERVERS: "{{ .Values.config.bootstrapServers }}"
  DYNAMIC_CONFIG_ENABLED: "{{ .Values.config.dynamicConfigEnabled }}"
