replicaCount: 2

image:
  repository: provectuslabs/kafka-ui
  tag: latest

service:
  port: 8080

config:
  clusterName: "prod-cluster"
  bootstrapServers: "broker.prod.svc.cluster.local:29092"
  dynamicConfigEnabled: "false"
