replicaCount: 1

image:
  repository: lordsecond/configserver
  tag: latest

server:
  port: 8888

service:
  type: ClusterIP

config:
  searchLocation: "file:/config/"

fluentd:
  enabled: true
  address: fluentd.logging.svc.cluster.local:24224
