replicaCount: 1

image:
  repository: grafana/grafana
  tag: 10.1.0

service:
  port: 3000

config:
  anonymousEnabled: "true"
  anonymousOrgRole: "Viewer"
  disableLoginForm: "false"

datasources:
  prometheus:
    url: "http://prometheus.dev.svc.cluster.local:9090"
  tempo:
    url: "http://tempo.dev.svc.cluster.local:3200"
  loki:
    url: "http://loki.dev.svc.cluster.local:3100"
