---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: broker
  template:
    metadata:
      labels:
        app: broker
    spec:
      enableServiceLinks: false
      containers:
        - name: broker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.ports.external }}
            - containerPort: {{ .Values.ports.internal }}
          env:
            - name: KAFKA_BROKER_ID
              valueFrom:
                configMapKeyRef:
                  key: KAFKA_BROKER_ID
                  name: {{ .Release.Name }}-config
            - name: KAFKA_ZOOKEEPER_CONNECT
              valueFrom:
                configMapKeyRef:
                  key: KAFKA_ZOOKEEPER_CONNECT
                  name: {{ .Release.Name }}-config
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              valueFrom:
                configMapKeyRef:
                  key: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
                  name: {{ .Release.Name }}-config
            - name: KAFKA_ADVERTISED_LISTENERS
              valueFrom:
                configMapKeyRef:
                  key: KAFKA_ADVERTISED_LISTENERS
                  name: {{ .Release.Name }}-config
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              valueFrom:
                configMapKeyRef:
                  key: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
                  name: {{ .Release.Name }}-config
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    app: broker
  ports:
    - protocol: TCP
      port: {{ .Values.ports.external }}
      targetPort: {{ .Values.ports.external }}
      name: kafka
    - protocol: TCP
      port: {{ .Values.ports.internal }}
      targetPort: {{ .Values.ports.internal }}
      name: kafka-internal
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  KAFKA_BROKER_ID: "{{ .Values.config.brokerId }}"
  KAFKA_ZOOKEEPER_CONNECT: "{{ .Values.config.zookeeperConnect }}"
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "{{ .Values.config.listenerSecurityProtocolMap }}"
  KAFKA_ADVERTISED_LISTENERS: "{{ .Values.config.advertisedListeners }}"
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "{{ .Values.config.offsetsTopicReplicationFactor }}"
