global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:9000'] ## only for demo purposes don't use host.docker.internal in production replace with the container name
  - job_name: 'exercise'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080'] ## only for demo purposes don't use host.docker.internal in production replace with the container name
        labels:
          application: 'Exercise Service'
  - job_name: 'workout'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8081'] ## only for demo purposes don't use host.docker.internal in production replace with the container name
        labels:
          application: 'Workout Service'
  - job_name: 'validation'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8082'] ## only for demo purposes don't use host.docker.internal in production replace with the container name
        labels:
          application: 'Validation Service'
  - job_name: 'notification'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8083'] ## only for demo purposes don't use host.docker.internal in production replace with the container name
        labels:
          application: 'Notification Service'