---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              valueFrom:
                configMapKeyRef:
                  key: ZOOKEEPER_CLIENT_PORT
                  name: {{ .Release.Name }}-config
            - name: ZOOKEEPER_TICK_TIME
              valueFrom:
                configMapKeyRef:
                  key: ZOOKEEPER_TICK_TIME
                  name: {{ .Release.Name }}-config
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    app: zookeeper
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  ZOOKEEPER_CLIENT_PORT: "{{ .Values.config.clientPort }}"
  ZOOKEEPER_TICK_TIME: "{{ .Values.config.tickTime }}"
