replicaCount: 2

image:
  repository: prom/prometheus
  tag: v2.46.0

service:
  port: 9090

config:
  global:
    scrapeInterval: 15s
    evaluationInterval: 15s
  scrapeConfigs:
    - jobName: "gateway"
      metricsPath: "/actuator/prometheus"
      targets:
        - "gateway.prod.svc.cluster.local:9000"
    - jobName: "exercise"
      metricsPath: "/actuator/prometheus"
      targets:
        - "exercise.prod.svc.cluster.local:8080"
      labels:
        application: "Exercise Service"
