apiVersion: apps/v1
kind: Deployment
metadata:
  name: fitplanfrontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fitplanfrontend
  template:
    metadata:
      labels:
        app: fitplanfrontend
    spec:
      containers:
        - name: fitplanfrontend
          image: lordsecond/fitplanfrontend:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: fitplanfrontend
spec:
  selector:
    app: fitplanfrontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80