apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: lordsecond/gateway:latest
          ports:
            - containerPort: 9000
          env:
            - name: SPRING_CONFIG_IMPORT
              value: "optional:configserver:http://configserver:8888"
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER-URI
              valueFrom:
                configMapKeyRef:
                  key: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER-URI
                  name: gateway-config
            - name: LOKI_URL
              valueFrom:
                configMapKeyRef:
                  key: LOKI_URL
                  name: common-config
            - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  key: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
                  name: common-config
            - name: EXERCISE_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  key: EXERCISE_SERVICE_URL
                  name: common-config
            - name: WORKOUT_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  key: WORKOUT_SERVICE_URL
                  name: common-config
            - name: VALIDATION_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  key: VALIDATION_SERVICE_URL
                  name: common-config
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  selector:
    app: gateway
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
data:
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER-URI: "http://keycloak.default.svc.cluster.local:8080/realms/spring-microservices-security-realm"