apiVersion: apps/v1
kind: Deployment
metadata:
  name: validation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: validation
  template:
    metadata:
      labels:
        app: validation
    spec:
      initContainers:
        - name: wait-for-configserver
          image: busybox
          command: [ 'sh', '-c', 'until nc -z configserver.default.svc.cluster.local 8888; do echo waiting for configserver; sleep 5; done' ]
      containers:
        - name: validation
          image: lordsecond/validation:latest
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openai-secret
                  key: OPENAI_API_KEY
            - name: LOKI_URL
              valueFrom:
                configMapKeyRef:
                  key: LOKI_URL
                  name: common-config
            - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  key: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
                  name: common-config
            - name: SPRING_CONFIG_IMPORT
              value: "optional:configserver:http://configserver.default.svc.cluster.local:8888"
          ports:
            - containerPort: 8082
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 60
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 60
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: validation
spec:
  selector:
    app: validation
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
---
apiVersion: v1
kind: Secret
metadata:
  name: openai-secret
type: Opaque
data:
  OPENAI_API_KEY: c2stcHJvai1CQW8zcnd6NkkxdnZtU2JpNXFmQlFlZHYtR2ZfSEJNTUVlc3ZrWm8yMDhSSVB6YW9yQkpHcUNkQW5kbF9QeHl3VFRfVWlnY190TlQzQmxia0ZKMDBTcThmMUZIWWt2Z0hQUjZXczlYSU5qbVZFcS12bFNqME1FRmNnRzlhYWVlOW84UU1oTlpabExwZHJiYjdvX05DbzZ6VklqWUE=