apiVersion: apps/v1
kind: Deployment
metadata:
  name: validation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: validation
  template:
    metadata:
      labels:
        app: validation
    spec:
      containers:
        - name: validation
          image: lordsecond/validation:latest
          env:
            #- name: SPRING_DATASOURCE_URL
            #  valueFrom:
            #    configMapKeyRef:
            #      key: SPRING_DATASOURCE_URL
            #      name: inventory-service-config
            - name: LOKI_URL
              valueFrom:
                configMapKeyRef:
                  key: LOKI_URL
                  name: common-config
            - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  key: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
                  name: common-config
            - name: SPRING_CONFIG_IMPORT
              value: "optional:configserver:http://configserver.default.svc.cluster.local:8888"
---
apiVersion: v1
kind: Service
metadata:
  name: validation
spec:
  selector:
    app: validation
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: validation-config
#data:
  #SPRING_DATASOURCE_URL: "jdbc:mysql://mysql.default.svc.cluster.local:3306/inventory_service"