---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: fitplanfrontend
  template:
    metadata:
      labels:
        app: fitplanfrontend
    spec:
      containers:
        - name: fitplanfrontend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env:
            - name: LOGGING_DRIVER
              value: fluentd
            - name: FLUENTD_ADDRESS
              value: fluentd.logging.svc.cluster.local:24224
          ports:
            - containerPort: {{ .Values.service.port }}
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.port }}
            initialDelaySeconds: 60
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.port }}
            initialDelaySeconds: 60
            periodSeconds: 20
          volumeMounts:
            - name: logs
              mountPath: /var/log
      volumes:
        - name: logs
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nodeport
spec:
  type: NodePort
  selector:
    app: fitplanfrontend
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  sessionAffinity: ClientIP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app: fitplanfrontend
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
